name: Changeset Update

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changeset Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 17.4.0
        uses: actions/setup-node@v3
        with:
          node-version: v17.4.0
          cache: "npm"

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}